class RoutePaths {
  const RoutePaths._();

  static const splash = '/';
  static const login = '/login';
  static const register = '/register';
  static const webAdminRequired = '/web-admin-required';
  static const main = '/main';
  static const legacyHome = '/home';
  static const tenant = '/tenant';
  static const home = tenant;
  static const search = '/houses';
  static const houseList = '/house-list';
  static const houseSearch = '/house-search';
  static const houseSearchResult = '/house-search-result';
  static const houseFilter = '/house-filter';
  static const houseDetail = '/houses/:houseId';
  static const appointment = '/appointment';
  static const realNameAuth = '/real-name-auth';
  static const profile = '/profile';
  static const profileEdit = '/profile/edit';
  static const settings = '/profile/settings';
  static const lease = '/leases';
  static const leaseDetail = ':leaseId';
  static const rentOrders = '/rent-orders';
  static const bill = '/bill';
  static const lock = '/lock';
  static const unlockRecords = '/locks/records';
  static const repair = '/repair';
  static const repairs = '/repairs';
  static const createRepair = '/repairs/create';
  static const repairDetail = '/repairs/:repairId';
  static const repairRecords = '/repairs/records';
  static const messageCenter = '/messages';
  static const customerService = '/customer-service';
  static const viewingAppointment = '/rental-flow/:houseId/viewing-appointment';
  static const viewingDetail = '/rental-flow/:houseId/viewing-detail';
  static const rentalApplication = '/rental-flow/:houseId/rental-application';
  static const realNameVerify = '/rental-flow/:orderId/real-name';
  static const leaseContract = '/rental-flow/:orderId/contract';
  static const rentalPayment = '/rental-flow/:orderId/payment';
  static const onlineSign = '/rental-flow/:orderId/sign';
  static const moveInComplete = '/rental-flow/:orderId/success';
  static const staff = '/staff';
  static const staffLockInit = '/staff/locks/init';
  static const staffLockManage = '/manage';
  static const staffDebug = '/staff/debug';
}
